# See https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_configuration_properties for configuring the MCP server
server:
  port: 8082
spring:
  ai.mcp:
    server:
        name: mcp-java-skeleton
        version: 1.0.0
        instructions: "This server provides job information tools and resources."
        protocol: STREAMABLE
        # TODO: Update based on your needs
        # Verify configuration properties at https://docs.spring.io/spring-ai/reference/1.1-SNAPSHOT/api/mcp/mcp-streamable-http-server-boot-starter-docs.html
        streamable-http:
          mcp-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
---

spring:
  config:
    activate:
      on-profile: env-local
http.monitor.port: 8080

---

spring:
  config:
    activate:
      on-profile: env-qa

---

spring:
  config:
    activate:
      on-profile: env-prod
